#!/usr/bin/python3

import os
import sys
import re

msgid = sys.argv[1]

# Extract msgid from URL
match = re.compile("mid:(///)?(.*@[^/]*)(/.*)?").match(msgid)
if match:
    msgid = match.group(2)

os.spawnl(os.P_WAIT, "/usr/bin/gnome-terminal", "gnome-terminal", "--",
          "/home/rhertzog/bin/my-open-msgid", msgid)
